Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 30

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/SignalException:
  Enabled: false