inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "spec/rails_helper.rb"
